apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: eu

resources:
  - ../../base
  - namespace.yaml

configMapGenerator:
  - name: region-config
    behavior: replace
    literals:
      - REGION=eu
      - KAFKA_CLUSTER_ID=xv7-R_BwRZq3LcZqLWLFKQ
