apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: shared

resources:
  - namespace.yaml
  - schema-registry.yaml
  - mirrormaker.yaml

commonLabels:
  app.kubernetes.io/part-of: redis-kafka-wal
