apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ap

resources:
  - ../../base
  - namespace.yaml

configMapGenerator:
  - name: region-config
    behavior: replace
    literals:
      - REGION=ap
      - KAFKA_CLUSTER_ID=ywERZ17hQRumFE7DsGsyJw
